### ISSUE TITLE
Workflow don't work anymore. after last update 1.0.25

### ISSUE THREAD

**Issue by NicolasGrimonpont** [schwark/alfred-smartthings-py#2]
The workflow don't work anymore for me after last update. Was working perfectly before.
I tried to download again from packal, but the same..

The workflow don't let me use any command after the keyword, like apikey, run, etc.. 
But make a search on google..

**Comment by schwark** [comment]
fixed by b1c3b88a3581b0c5f5b418ab5eff76a412927097

**Comment by NicolasGrimonpont** [comment]
Thank you schwark, work fine !!!
